project:
  type: website      # or "default" if youâ€™re not using website features
  output-dir: _quarto_rendered  # or e.g. "../docs/flytskjema"

format:
  html:
    lang: nb
    language:
      label:
        fig: "Figur"